<?php

/**
 * @file
 * PhpStorm module file.
 */

/**
 * Implements hook_menu().
 */
function phpstorm_menu() {
  $items['phpstorm'] = array(
    'title' => 'PhpStorm Page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('phpstorm_example_form'),
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  return $items;
}

/**
 * PhpStorm form.
 */
function phpstorm_example_form($form, &$form_state) {
  $form['test'] = [
    '#type' => 'fieldset',
    '#title' => t('Title'),
    '#weight' => 0,
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  ];
  $form['content'] = [
    '#markup' => '<p>Test</p>',
    '#weight' => 1,
  ];

  $form[''] = [
    '#type' => 'textfield',
    '#title' => t('Title'),
    '#default_value' => 'akjsdh',
    '#size' => 64,
    '#maxlength' => 128,
  ];

  return $form;
}
